#!/bin/bash
set +e
source /etc/code-server-hub/ENVSFILE
set -x

ROOTOWNER=$(stat -c '%U' /root)
if [ "$ROOTOWNER" != "$USERNAME" ]; then
    echo "First run, initing"
    useradd -u $USERUID -d /root $USERNAME
    usermod -aG sudo $USERNAME
    chown $USERNAME:$USERNAME /root
    chown $USERNAME:$USERNAME /etc/code-server-hub/.cshub
    chmod 700 /root
    chmod -R 700 /root/.oh-my-zsh
    chown -R $USERNAME:$USERNAME /root
    git config --global user.email "$USERNAME@example.com"
    git config --global user.name $USERNAME
fi

/etc/init.d/cron start

echo "rcS finished. Runing /etc/rc.local"
parser=$(head -n 1 /etc/rc.local)
eval ${parser:2} /etc/rc.local &
