#!/bin/bash
set +e
source /etc/code-server-hub/ENVSFILE
set -x

ROOTOWNER=$(stat -c '%U' /root)
if [ "$ROOTOWNER" != "$USERNAME" ]; then
    echo "First run, initing"
    ln -s /home/$USERNAME /root/$USERNAME
    ln -s /data /root/data
    echo "export PATH=$PATH:/usr/local/cuda/bin" > /etc/profile.d/20-nvcc.sh
    useradd -u $USERUID -d /root $USERNAME --no-log-init
    usermod -aG sudo $USERNAME
    usermod -aG root $USERNAME

    mkdir -p /root/.cache
    mkdir -p /home/$USERNAME/.cache/huggingface
    ln -s /home/$USERNAME/.cache/huggingface /root/.cache/huggingface
    chown $USERNAME:$USERNAME /home/$USERNAME/.cache/huggingface

    mkdir -p /home/$USERNAME/.conda/envs
    rm -r /opt/miniconda/envs
    ln -s /home/$USERNAME/.conda/envs /opt/miniconda/envs
    chown $USERNAME:$USERNAME /home/$USERNAME/.conda/envs

    groupmod -g $USERGID $USERNAME
    git config --global user.email "$USERNAME@example.com"
    git config --global user.name $USERNAME
    set +x
    echo "conda init --all"
    eval "$(/opt/miniconda/bin/conda shell.bash hook)"
    conda init --all
    set -x
    chmod 700 /root
    chmod -R 700 /root/.oh-my-zsh
    chown -R $USERNAME:$USERNAME /root
    if [ ! -f "/home/$USERNAME/data" ] && [ ! -d "/home/$USERNAME/data" ]; then
        ln -s /data /home/$USERNAME/data || true
    fi
fi

/etc/init.d/cron start

echo "rcS finished. Runing /etc/rc.local"
parser=$(head -n 1 /etc/rc.local)
eval ${parser:2} /etc/rc.local &
