#!/bin/sh
source /etc/code-server-hub/ENVSFILE
/etc/init.d/rcS
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
export LD_PRELOAD=/lib/runit-docker.so
export KALDI_DIR=/usr/share/kaldi-asr/tools
set +e
source /usr/local/bin/virtualenvwrapper.sh
source /etc/profile
exec runsvdir /etc/service
