FROM ubuntu

COPY install_1_requirement.sh /tmp/install.sh
RUN  chmod 755 /tmp/install.sh ; /tmp/install.sh; rm /tmp/install.sh

#COPY install_2_optional_useful.sh /tmp/install2.sh 
#RUN  chmod 755 /tmp/install2.sh; /tmp/install2.sh; rm /tmp/install2.sh

#COPY install_3_optional_kaldi.sh /tmp/install3.sh 
#RUN  chmod 755 /tmp/install3.sh; /tmp/install3.sh; rm /tmp/install3.sh

#COPY install_4_optional_espnet.sh /tmp/install4.sh 
#RUN  chmod 755 /tmp/install4.sh; /tmp/install4.sh; rm /tmp/install4.sh

#COPY install_5_optional_pykaldi.sh /tmp/install5.sh 
#RUN  chmod 755 /tmp/install5.sh; /tmp/install5.sh; rm /tmp/install5.sh

COPY move2docker /move2docker
RUN  rsync -a --no-perms --no-owner --no-group --chmod=755 --keep-dirlinks /move2docker/* / ;/tmp/install2.sh; rm -r /move2docker

ENV CUDA_DEVICE_ORDER=PCI_BUS_ID \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    NVIDIA_DRIVER_CAPABILITIES=all \
    MKL_DEBUG_CPU_TYPE=5

ENTRYPOINT ["/sbin/runit-docker"]

