#!/bin/sh
source /etc/code-server-hub/ENVSFILE
/etc/init.d/rcS
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
source /usr/local/bin/virtualenvwrapper.sh
export LD_PRELOAD=/lib/runit-docker.so
#workon env_name
exec runsvdir /etc/service
