#!/bin/bash
source /etc/code-server-hub/ENVSFILE
set +e
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
export LD_PRELOAD=/lib/runit-docker.so
export KALDI_DIR=/usr/share/kaldi-asr/tools
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
source /etc/profile
/etc/init.d/rcS
exec runsvdir /etc/service
