
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-29T10:09:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "be4c0637192c50e257f743198e30a9f0706b0724",
 "version": "1.0.0b12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
